# Generated by Django 5.2.6 on 2025-09-22 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_aluno', models.CharField(max_length=150)),
                ('endereco', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('nasc', models.DateField()),
                ('sexo', models.CharField(max_length=250)),
                ('cpf', models.CharField(max_length=11)),
                ('telefone', models.CharField(max_length=15)),
                ('cep', models.CharField(max_length=8)),
                ('bairro', models.CharField(max_length=150)),
                ('cidade', models.CharField(max_length=250)),
                ('uf', models.CharField(max_length=2)),
                ('matricula', models.CharField(max_length=150)),
                ('curso', models.CharField(max_length=250)),
                ('serie', models.IntegerField()),
                ('turno', models.CharField(max_length=150)),
                ('observacoes', models.TextField()),
            ],
        ),
    ]
